sudo: false
language: ruby
rvm:
  - 2.5.0
before_install: gem install bundler -v 1.16.1

language: ruby

rvm:
  - 2.5.0

env:
  - DB=pgsql

services:
  - postgresql

before_script:
  - cp spec/dummy/config/database.travis.yml spec/dummy/config/database.yml

script:
  - cd spec/dummy && RAILS_ENV=test bundle exec rake db:create db:schema:load && cd ../..
  - bundle exec rspec
